# https://github.com/boratanrikulu/eternity
baseURL: https://sylvie-laufeydottir.github.io # todo: change site url.
title: Kyuubi.ART # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.


params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: '' # todo: change default subtitle for your website.
  copyright: 京ICP备2020037990号-2 # todo: set your copyright type.
  author: Sylvie Laufeydottir # todo: set your full name.
  dontShowSource: true # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: add your social accounts.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:murphy@photographer.net'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/Sylvie-Laufeydottir'
      landing: true
  homepage: "/work" # todo: uncomment homepage, homepage link is mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '1111' # todo: set your plausible id.
  disableWelcomePageBackground: false # disables the background image on the homepage
  disableRadius: false
  moveIt: false # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: people
      url: /tags/people/
      weight: 2
    - name: space
      url: /tags/space
      weight: 3
    - name: nature
      url: /tags/nature/
      weight: 4
    - name: archive
      url: /tags/archive/
      weight: 5
    - name: about
      url: /about/
      weight: 6
